-- Inserts para public."Cuerpos_Bomberos" generados desde src/utils/constants.js
-- No inserta el ID porque Id_Cuerpo_Bomberos es identity/autogenerado.

BEGIN;

INSERT INTO public."Cuerpos_Bomberos" ("Nombre", "Region")
VALUES
  ('Cuerpo de Bomberos Cartagena', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Achao', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Algarrobo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Alto Hospicio', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Ancud', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Andacollo', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Angol', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Antilhue', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Antofagasta', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Antuco', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Arauco', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Arica', 'Region de Arica y Parinacota'),
  ('Cuerpo de Bomberos de Buin', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Bulnes', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Cabildo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Cabrero', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Calama', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Calbuco', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Caldera', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Camina', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Candela', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Canete', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Capitan Pastene', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Carahue', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Carretera Austral', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Casablanca', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Castro', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Catemu', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Cauquenes', 'Region del Maule'),
  ('Cuerpo de Bomberos de Chacao', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Chaiten', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Chanaral', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Chanco', 'Region del Maule'),
  ('Cuerpo de Bomberos de Chepica', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Cherquenco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Chiguayante', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Chile Chico', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Chillan', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Chimbargongo', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Chol Chol', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Chonchi', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Choshuenco', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Cobquecura', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Cochamo', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Cochrane', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Codegua', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Coelemu', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Coihueco', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Coinco', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Colbun', 'Region del Maule'),
  ('Cuerpo de Bomberos de Colina', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Collipulli', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Coltauco', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Combarbala', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Concepcion', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Conchali-Huechuraba', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Constitucion', 'Region del Maule'),
  ('Cuerpo de Bomberos de Contulmo', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Copiapo', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Coquimbo', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Coronel', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Corral', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Corte Alto', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Coyhaique', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Crucero', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Cumpeo', 'Region del Maule'),
  ('Cuerpo de Bomberos de Cunco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Curacautin', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Curacavi', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Curaco de Velez', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Curanilahue', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Curarrehue', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Curepto', 'Region del Maule'),
  ('Cuerpo de Bomberos de Curico', 'Region del Maule'),
  ('Cuerpo de Bomberos de Dalcahue', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Diego de Almagro', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Donihue', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de El Carmen', 'Region del Nuble'),
  ('Cuerpo de Bomberos de El Monte', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de El Palqui', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de El Quisco', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de El Tabo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Empedrado', 'Region del Maule'),
  ('Cuerpo de Bomberos de Entre Lagos', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Ercilla', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Florida', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Freire', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Freirina', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Fresia', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Frutillar', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Futaleufu', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Futrono', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Galvarino', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Gorbea', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Graneros', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Hijuelas', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Hualaihue', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Hualane', 'Region del Maule'),
  ('Cuerpo de Bomberos de Hualqui', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Huapen', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Huara', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Huasco', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Huellelhue', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Huepil', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Illapel', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Inca de Oro', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Iquique', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Isla de Maipo', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Isla de Pascua', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de La Calera', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de La Cruz', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de La Estrella', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de La Granja San Ramon y La Pintana', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de La Higuera', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de La Lanco', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de La Ligua', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de La Serena', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de La Union', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Lago Ranco', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Laja', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Las Cabras', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Las Cascadas', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Las Vilos', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Lastarria', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Lautaro', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Lebu', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Lican Ray', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Licanten', 'Region del Maule'),
  ('Cuerpo de Bomberos de Limache', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Linares', 'Region del Maule'),
  ('Cuerpo de Bomberos de Litueche', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Llanquihue', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Llay-Llay', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Llico', 'Region del Maule'),
  ('Cuerpo de Bomberos de Lolol', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Loncoche', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Longavi', 'Region del Maule'),
  ('Cuerpo de Bomberos de Lonquimay', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Los alamos', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Los angeles', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Los Lagos', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Los Muermos', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Los Sauces', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Lota', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Lumaco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Machali', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Mafil', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Maipu', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Malalhue', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Malloa', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Marchigue', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Maria Elena', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Maria Pinto', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Maule', 'Region del Maule'),
  ('Cuerpo de Bomberos de Maullin', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Mehuin', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Mejillones', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Melinka', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Melipilla', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Mellipeuco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Molina', 'Region del Maule'),
  ('Cuerpo de Bomberos de Mulchen', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Nacimiento', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Nancagua', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Navidad', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Negrete', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Ninhue', 'Region del Nuble'),
  ('Cuerpo de Bomberos de nipas', 'Region del Nuble'),
  ('Cuerpo de Bomberos de niquen', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Nogales', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Nueva Imperial', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de nunoa', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Olivar', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Olmue', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Osorno', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Ovalle', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Paihuano', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Paillaco', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Paine', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Palena', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Palmilla', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Panguipulli', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Papudo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Paredones', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Parral', 'Region del Maule'),
  ('Cuerpo de Bomberos de Pelarco', 'Region del Maule'),
  ('Cuerpo de Bomberos de Pelluhue', 'Region del Maule'),
  ('Cuerpo de Bomberos de Pemuco', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Penaflor', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Pencahue', 'Region del Maule'),
  ('Cuerpo de Bomberos de Penco', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Peralillo', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Perquenco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Petorca', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Peumo', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Pica', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Pichidegua', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Pichilemu', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Pichirropulli', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Pinto', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Pitrufquen', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Placilla', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Portezuelo', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Porvenir', 'Region de Magallanes y Antartica Chilena'),
  ('Cuerpo de Bomberos de Pozo Almonte', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Puchuncavi', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Pucon', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Puente Alto', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Puerto Aysen', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Puerto Cisnes', 'Region de Aysen'),
  ('Cuerpo de Bomberos de Puerto Montt', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Puerto Natales', 'Region de Magallanes y Antartica Chilena'),
  ('Cuerpo de Bomberos de Puerto Octay', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Puerto Saavedra', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Puerto Varas', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Puerto Williams', 'Region de Magallanes y Antartica Chilena'),
  ('Cuerpo de Bomberos de Pumanque', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Punitaqui', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Punta Arenas', 'Region de Magallanes y Antartica Chilena'),
  ('Cuerpo de Bomberos de Puqueldon', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Puren', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Purranque', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Putaendo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Queilen', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Quellon', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Quemchi', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Quilaco', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Quilicura', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Quilleco', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Quillon', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Quillota', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Quilpue', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Quinta de Tilcoco', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Quinta Normal', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Quintero', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Quirihue', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Quitratue', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Rancagua', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Rauco', 'Region del Maule'),
  ('Cuerpo de Bomberos de Renaico', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Rengo', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Requinoa', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Retiro', 'Region del Maule'),
  ('Cuerpo de Bomberos de Reumen', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Riachuelo', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Rinconada', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Rio Bueno', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Rio Hurtado', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Rio Negro', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de Romeral', 'Region del Maule'),
  ('Cuerpo de Bomberos de Sagrada Familia', 'Region del Maule'),
  ('Cuerpo de Bomberos de Salamanca', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de San Antonio', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de San Bernardo', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de San Carlos', 'Region del Nuble'),
  ('Cuerpo de Bomberos de San Clemente', 'Region del Maule'),
  ('Cuerpo de Bomberos de San Esteban', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de San Felipe', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de San Fernando', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de San Francisco de Mostazal', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de San Ignacio', 'Region del Nuble'),
  ('Cuerpo de Bomberos de San Javier', 'Region del Maule'),
  ('Cuerpo de Bomberos de San Jose De La Mariquina', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de San Jose de Maipo', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de San Juan De La Costa', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de San Nicolas', 'Region del Nuble'),
  ('Cuerpo de Bomberos de San Pablo', 'Region de Los Lagos'),
  ('Cuerpo de Bomberos de San Pedro de Atacama', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de San Pedro de la Paz', 'Region del Biobio'),
  ('Cuerpo de Bomberos de San Pedro de Melipilla', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de San Rafael', 'Region del Maule'),
  ('Cuerpo de Bomberos de San Rosendo', 'Region del Biobio'),
  ('Cuerpo de Bomberos de San Vicente de Tagua Tagua', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Santa Barbara', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Santa Cruz', 'Region del Libertador General Bernardo OHiggins'),
  ('Cuerpo de Bomberos de Santa Juana', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Santa Maria', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Santa Rosa de Huantajaya', 'Region de Tarapaca'),
  ('Cuerpo de Bomberos de Santiago', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Santo Domingo', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Sierra Gorda', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Talagante', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Talca', 'Region del Maule'),
  ('Cuerpo de Bomberos de Talcahuano', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Taltal', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Temuco', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Teno', 'Region del Maule'),
  ('Cuerpo de Bomberos de Teodoro Schmidt', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Tierra Amarilla', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Til-til', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Tirua', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Tocopilla', 'Region de Antofagasta'),
  ('Cuerpo de Bomberos de Tolten', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Tome', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Traiguen', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Trehuaco', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Valdivia', 'Region de Los Rios'),
  ('Cuerpo de Bomberos de Vallenar', 'Region de Atacama'),
  ('Cuerpo de Bomberos de Valparaiso', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Victoria', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Vicuna', 'Region de Coquimbo'),
  ('Cuerpo de Bomberos de Vilcun', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Villa Alegre', 'Region del Maule'),
  ('Cuerpo de Bomberos de Villa Alemana', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Villa Alhue', 'Region de Metropolitana'),
  ('Cuerpo de Bomberos de Villarrica', 'Region de La Araucania'),
  ('Cuerpo de Bomberos de Vina del Mar', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos de Yerbas Buenas', 'Region del Maule'),
  ('Cuerpo de Bomberos de Yumbel', 'Region del Biobio'),
  ('Cuerpo de Bomberos de Yungay', 'Region del Nuble'),
  ('Cuerpo de Bomberos de Zapallar', 'Region de Valparaiso'),
  ('Cuerpo de Bomberos Metropolitano Sur', 'Region de Metropolitana');

COMMIT;
